[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_assistant_parsers_core"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["ai_assistant_parsers_core", "ai_assistant_parsers_core.*"]